### PR TITLE
new addtion of token detail

### PR DESCRIPTION
**Pull request by kuro39**
This is request to update custom token.

### CODE REVIEW

**Comment by kuro39** [comment]
if there is any issue please let me know.

**Comment by kuro39** [comment]
HI team,

Thanks for accept my request.

I confirmed blocksscan page though, it still doesn't show the token icon
image.

https://xdcscan.io/token/0x70D5d8Fe16e2CF794f8EF2C731D1BE91d704c585

May I know if it will be shown icon image on this site with I just wait for
a few days?

Regards,


2024年7月13日(土) 20:40 BlocksScan Explorer ***@***.***>:

**Comment by BlocksScanIO** [comment]
Hello,

Can you check now.

Regards,

Support Team.  
Blocksscan Technologies Pvt Ltd.
Email - ***@***.***
Web   - www.blocksscan.com / www.blocksscan.io 

----------------------------------------

**Comment by kuro39** [comment]
Hi team,
Thank you very much, I now confirmed it's shown.

I have one more question.
I imported this token into XDC pay though, the icon still doesn't show.
May I know if your team also take care of XDC pay, or any other team does?

Regards,


2024年7月14日(日) 11:49 BlocksScan Explorer ***@***.***>:

**Pull request merged**
